12 sprint genre and year popular
Kirill495/java-filmorate pull request #8
Opened 2023-11-30 11:26 UTC by DashaTrut

2023-11-30 22:00 UTC, Kirill495 requested changes
Посмотри мои замечания, пожалуйста.
Если будут вопросы - пиши в телеграме.

2023-11-30 22:00 UTC, Kirill495 commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS mpa_rating (
А зачем ты CREATE на мал буквы исправила?

2023-12-03 10:05 UTC, dsergeyg commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        fillInGenres(films);
В идеале нужно забрать изменения по ветке add-director после апрува, в метод getMostPopularFilms добавить fillInDirectors(films);

2023-12-03 13:58 UTC, DashaTrut commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +
не имеет отношения к коду

2023-12-03 16:15 UTC, Kirill495 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (year == null & genreId == null) {
С чем именно ты не согласна?

2023-12-03 19:25 UTC, Kirill495 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        fillInGenres(films);
Ветку с режиссерами добавил в develop. Даша, можешь дорабатывать.

2023-12-04 21:23 UTC, dsergeyg approved these changes

2023-12-05 03:35 UTC, Kirill495 approved these changes

2023-12-05 03:35 UTC, merged