12 sprint remove user, film
Kirill495/java-filmorate pull request #9
Opened 2023-11-30 17:49 UTC by DashaTrut

2023-11-30 20:21 UTC, Kirill495 requested changes

2023-11-30 20:21 UTC, Kirill495 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public boolean filmDelete(int filmId);
см. замечание к имени метода выше.

2023-11-30 20:21 UTC, Kirill495 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        throw new UnsupportedOperationException();
Надо указать причину, почему выбрасываешь исключение.

2023-12-03 14:05 UTC, DashaTrut commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return jdbcTemplate.update(sqlQuery, userId) > 0;
подтверждения этому доводу я не нашла

2023-12-03 19:24 UTC, fanast31 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return jdbcTemplate.update(sqlQuery, userId) > 0;
Я тоже без try catch делал везде - все проверки включая ревью, прошли. Мы же попадем в ошибку ErrorHandler и там в логи выведется все.

2023-12-04 14:57 UTC, Kirill495 approved these changes

2023-12-05 03:58 UTC, merged